name: Build

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: RakambdaOrg/rakambda-github-workflows/.github/workflows/gradle-build.yml@main
    with:
      java-version: ${{ vars.JAVA_VERSION }}
