name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: Rakambda/rakambda-github-workflows/.github/workflows/gradle-build.yml@main
    with:
      java-version: ${{ vars.JAVA_VERSION }}